---

- name: "Install default useful programs"
  become: true
  apt:
    pkg:
      - vim-nox
      - zsh
      - git

- name: "Install Ohmyzsh"
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: true

- name: "Installtion of Vundle"
  shell: git clone https://github.com/VundleVim/Vundle.vim.git {{ vundle_location }}
  ignore_errors: true
