---

- name: "Install default useful programs"
  become: true
  apt:
    pkg:
      - vim-nox
      - zsh
      - git
      - build-essential
      - cmake
      - python3-dev
      
- name: "Ohmyzsh folder"
  stat:
    path: "{{ ohmyzsh_path }}"
  register: ohmyzsh_path

- name: "Install Ohmyzsh"
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_path.stat.exists

- name: "Installation of Vundle"
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ vundle_location }}"

- include: ohmyzsh_plugins.yml
