---

- name: "Install default useful programs"
  become: true
  apt:
    pkg:
      - vim-nox
      - zsh
      - git
      - build-essential
      - cmake
      - python3-dev

- name: "Install Ohmyzsh"
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: true

- name: "Installation of Vundle"
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ vundle_location }}"

- include: ohmyzsh_plugins.yml
