---

- name: "Check if oh my zsh is installed"
  stat:
    path: "{{ ohmyzsh_path }}"
  register: ohmyzsh_folder

- name: "Installing zsh-syntax-highlighting"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ohmyzsh_plugins_path }}/zsh-syntax-highlighting"
    version: "HEAD"
  when: not ohmyzsh_folder.stat.exists

- name: "Installing zsh-autosuggestions"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ohmyzsh_plugins_path }}/zsh-autosuggestions"
    version: "HEAD"
  when: not ohmyzsh_folder.stat.exists
